# -*- coding: utf-8 -*-
"""LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HT27OB2So_KMYDbh4zxd7hMsAxVJyDqg

# **list**
"""

import numpy as np
arr = np.arange(1, 11)
print (arr)

# Function to calculate sum, maximum, and minimum
def calculate_stats(numbers):
    total_sum = sum(numbers)  # Sum of all numbers
    max_num = max(numbers)    # Maximum value
    min_num = min(numbers)    # Minimum value

    return total_sum, max_num, min_num

# Sample list of numbers
numbers = [10, 20, 4, 56, 23, 98, 34]

# Call the function and store the results
total_sum, max_num, min_num = calculate_stats(numbers)

# Print the results
print(f"Sum: {total_sum}")
print(f"Maximum: {max_num}")
print(f"Minimum: {min_num}")

# Function to add elements to a list
def add_elements_to_list():
    elements = []  # Start with an empty list
    while True:
        # Ask the user to input a value
        element = input("Enter an element to add to the list (or 'done' to stop): ")

        # Check if the user wants to stop
        if element.lower() == 'done':
            break

        # Otherwise, add the element to the list
        elements.append(element)

    return elements

# Call the function and store the result
my_list = add_elements_to_list()

# Print the list after user input
print("Your final list is:", my_list)



"""# Tuples"""

# Creating a tuple with 5 fruit names
fruits = ("apple", "banana", "cherry", "date", "elderberry")

# Printing the tuple
print("Tuple of fruits:", fruits)

# Creating a tuple with mixed data types
my_tuple = ("Hello", 42, 3.14, True, "Python")

# Printing the tuple
print("Tuple with mixed data:", my_tuple)

"""# **Sets**"""

# Create two sets with common and unique elements
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Print the sets
print("Set 1:", set1)
print("Set 2:", set2)

# Common elements (intersection)
common_elements = set1.intersection(set2)
print("Common elements:", common_elements)

# Unique elements in set1 (difference)
unique_to_set1 = set1.difference(set2)
print("Unique to Set 1:", unique_to_set1)

# Unique elements in set2 (difference)
unique_to_set2 = set2.difference(set1)
print("Unique to Set 2:", unique_to_set2)

# Create a set of 10 students using (name, marks)
students = {
    ("Alice", 85),
    ("Bob", 78),
    ("Charlie", 92),
    ("David", 74),
    ("Eva", 88),
    ("Frank", 81),
    ("Grace", 95),
    ("Hannah", 69),
    ("Ian", 77),
    ("Jane", 90)
}

# Display all students
print("Set of 10 students (Name and Marks):")
for student in students:
    name, marks = student
    print(f"Name: {name}, Marks: {marks}")

# Create a set of 5 book names
books = {
    "To Kill a Mockingbird",
    "1984",
    "The Great Gatsby",
    "Pride and Prejudice",
    "The Hobbit"
}

# Print the set of books
print("Set of 5 books:")
for book in books:
    print(f"- {book}")



"""# ***Dictionaries***

# **Numpy**

# **Matplotlib**
"""